name: Generate Snake

on:
  schedule:
    - cron: "0 8 * * *"  # 8 AM
    - cron: "0 13 * * *" # 1 PM
    - cron: "0 16 * * *" # 4 PM
    - cron: "0 23 * * *" # 11 PM
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set Git Identity
        run: |
          git config --global user.name "Bramha Deshmukh"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Regeneration Marker
        run: |
          date > dist/last-updated.txt

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake animation"
          branch: main
          commit_options: --allow-empty
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
